############################################################
#
# web访问端口号  约定：8080
#
############################################################
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

############################################################
#
# FastDFS 配置
#
############################################################
fdfs:
  connect-timeout: 3000   # 连接的超时时间
  so-timeout: 3000        # 读取的超时时间
  tracker-list: 192.168.1.153:22122   # tracker IP地址和端口号

############################################################
#
# 上传大小控制
#
############################################################
spring:
  servlet:
    multipart:
      max-file-size: 5120000     # 文件上传大小限制为5m
      max-request-size: 5120000  # 请求大小限制为5m